CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(191) NOT NULL,
  email VARCHAR(191) NOT NULL UNIQUE,
  password VARCHAR(191) NOT NULL,
  role VARCHAR(32) NOT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  schoolId INT NULL,
  schoolName VARCHAR(191) NULL,
  lastLogin DATETIME NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS schools (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(191) NOT NULL,
  district VARCHAR(191) NOT NULL,
  address VARCHAR(255) NOT NULL,
  contact VARCHAR(191) NOT NULL,
  gps VARCHAR(64) NOT NULL DEFAULT '-',
  accreditation VARCHAR(8) NOT NULL DEFAULT 'B',
  accreditationScore INT NOT NULL DEFAULT 80,
  capacity INT NOT NULL DEFAULT 120,
  graduationRate INT NOT NULL DEFAULT 90,
  avgExam INT NOT NULL DEFAULT 80,
  achievements INT NOT NULL DEFAULT 10,
  certifiedTeachers INT NOT NULL DEFAULT 12,
  rating DECIMAL(3,1) NOT NULL DEFAULT 4.5,
  review TEXT NULL,
  description TEXT NULL,
  logo VARCHAR(255) NULL,
  facilities JSON NOT NULL,
  programs JSON NOT NULL,
  extracurriculars JSON NOT NULL,
  ratio VARCHAR(32) NOT NULL DEFAULT '1:10',
  gallery JSON NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS eligibility_submissions (
  id VARCHAR(64) PRIMARY KEY,
  submittedAt DATETIME NOT NULL,
  userEmail VARCHAR(191) NOT NULL,
  userName VARCHAR(191) NOT NULL,
  input JSON NOT NULL,
  result JSON NOT NULL,
  recommendations JSON NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS criteria_requests (
  id INT AUTO_INCREMENT PRIMARY KEY,
  schoolId INT NOT NULL,
  adminId INT NOT NULL,
  adminName VARCHAR(191) NOT NULL,
  schoolName VARCHAR(191) NOT NULL,
  oldCriteria JSON NOT NULL,
  newCriteria JSON NOT NULL,
  reason TEXT NOT NULL,
  status ENUM('pending', 'approved', 'rejected') NOT NULL DEFAULT 'pending',
  adminNote TEXT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (schoolId) REFERENCES schools(id) ON DELETE CASCADE,
  FOREIGN KEY (adminId) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS activity_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  actorId INT NULL,
  actorName VARCHAR(191) NOT NULL,
  actorEmail VARCHAR(191) NOT NULL,
  actorRole VARCHAR(32) NOT NULL,
  type VARCHAR(64) NOT NULL,
  description TEXT NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'success',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

