export const schools = [
  {
    id: 1,
    name: 'SD NEGERI 1 KRANJI',
    district: 'Purwokerto Timur',
    address: 'Jl. Jend. Sudirman Gg. Kranji No. 1, Purwokerto Timur',
    contact: '(0281) 635-123',
    gps: '-7.4251, 109.2432',
    accreditation: 'A',
    accreditationScore: 96,
    capacity: 220,
    graduationRate: 99,
    avgExam: 88,
    achievements: 45,
    certifiedTeachers: 28,
    rating: 4.9,
    review: 'Sekolah unggulan dengan program akademik dan non-akademik yang seimbang.',
    facilities: ['Lab Komputer', 'Perpustakaan Digital', 'Lapangan Olahraga Indoor'],
    programs: ['Kelas Akselerasi', 'STEM', 'Program Kewirausahaan'],
    extracurriculars: ['Robotik', 'Debat Bahasa Inggris', 'Orkestra'],
    ratio: '1:15',
    gallery: ['Foto Gedung', 'Foto Lab', 'Foto Kegiatan'],
  },
  {
    id: 2,
    name: 'SD NEGERI 1 SOKANEGARA',
    district: 'Purwokerto Timur',
    address: 'Jl. Dr. Soeparno No. 5, Sokanegara, Purwokerto Timur',
    contact: '(0281) 632-789',
    gps: '-7.4195, 109.2598',
    accreditation: 'A',
    accreditationScore: 94,
    capacity: 200,
    graduationRate: 97,
    avgExam: 86,
    achievements: 38,
    certifiedTeachers: 25,
    rating: 4.8,
    review: 'Lingkungan belajar yang nyaman dengan fokus pada pengembangan karakter.',
    facilities: ['Perpustakaan', 'Aula Serbaguna', 'Taman Belajar'],
    programs: ['Pendidikan Karakter', 'Literasi', 'Seni dan Budaya'],
    extracurriculars: ['Pramuka', 'Tari Tradisional', 'Paduan Suara'],
    ratio: '1:18',
    gallery: ['Foto Sekolah', 'Foto Perpustakaan', 'Foto Ekstrakurikuler'],
  },
]
